### ISSUE TITLE
use esp32 firebeetles v4.0, no text display

### ISSUE THREAD

**Issue by XinFan2022** [DFRobot/DFRobot_OLED12864#1]
我用esp32的firebeetles 4.0，arduino1.8.19版本，一年前用arduino上下的库文件，是可以显示中文，英文和符号的。但使用了现在Github的库文件和arduino上下的库文件，屏幕没有显示了。但是用时钟的例子是可以画出来的，不知道是不是库文件有问题还是我哪里用错了。

**Comment by qsjhyy** [comment]
之前忘了关注此库，所以没能第一时间知晓，刚刚看了邮件，才发现这里的反馈。应该就是字库芯片GT30L24A3W的片选引脚的拨码开关没有修改导致。此设置是避免引脚冲突，给你提供更多选项。之后我会通过添加注释和修改默认引脚的方法避免此类问题。谢谢！
